(defvar *continents*
  '((CONTINENT :name "Asia" :code AS)
 (CONTINENT :name "Europe" :code EU)
 (CONTINENT :name "Africa" :code AF)
 (CONTINENT :name "North America" :code NA)
 (CONTINENT :name "South America" :code SA)
 (CONTINENT :name "Australia & Oceania" :code AU)))

(defvar *countries*
  '((COUNTRY :NAME "Afghanistan" :CAPITAL "Kabul" :CONTINENTS (AS))
 (COUNTRY :NAME "Albania" :CAPITAL "Tirane" :CONTINENTS (EU))
 (COUNTRY :NAME "Algeria" :CAPITAL "Algers" :CONTINENTS (AF))
 (COUNTRY :NAME "Andorra" :CAPITAL "Andorra la Vella" :CONTINENTS (EU))
 (COUNTRY :NAME "Angola" :CAPITAL "Luanda" :CONTINENTS (AF))
 (COUNTRY :NAME "Antigua and Barbuda" :CAPITAL "St. John's" :CONTINENTS (NA))
 (COUNTRY :NAME "Argentina" :CAPITAL "Buenos Aires" :CONTINENTS (SA))
 (COUNTRY :NAME "Armenia" :CAPITAL "Yerevan" :CONTINENTS (EU))
 (COUNTRY :NAME "Australia" :CAPITAL "Canberra" :CONTINENTS (AU))
 (COUNTRY :NAME "Austria" :CAPITAL "Vienna" :CONTINENTS (EU))
 (COUNTRY :NAME "Azerbaijan" :CAPITAL "Baku" :CONTINENTS (AS))
 (COUNTRY :NAME "Bahamas" :CAPITAL "Nassau" :CONTINENTS (NA))
 (COUNTRY :NAME "Bahrain" :CAPITAL "Manama" :CONTINENTS (AS))
 (COUNTRY :NAME "Bangladesh" :CAPITAL "Dhaka" :CONTINENTS (AS))
 (COUNTRY :NAME "Barbados" :CAPITAL "Bridgetown" :CONTINENTS (NA))
 (COUNTRY :NAME "Belarus" :CAPITAL "Minsk" :CONTINENTS (EU))
 (COUNTRY :NAME "Belgium" :CAPITAL "Brussels" :CONTINENTS (EU))
 (COUNTRY :NAME "Belize" :CAPITAL "Belmopan" :CONTINENTS (NA))
 (COUNTRY :NAME "Benin" :CAPITAL "Port-Novo" :CONTINENTS (AF))
 (COUNTRY :NAME "Bhutan" :CAPITAL "Thimphu" :CONTINENTS (AS))
 (COUNTRY :NAME "Bolivia" :CAPITAL "Sucre" :CONTINENTS (SA))
 (COUNTRY :NAME "Bosnia and Herzegovina" :CAPITAL "Sarajevo" :CONTINENTS (EU))
 (COUNTRY :NAME "Botswana" :CAPITAL "Gaborone" :CONTINENTS (AF))
 (COUNTRY :NAME "Brazil" :CAPITAL "Brasilia" :CONTINENTS (SA))
 (COUNTRY :NAME "Brunei" :CAPITAL "Bander Seri Begawan" :CONTINENTS (AS))
 (COUNTRY :NAME "Bulgaria" :CAPITAL "Sofia" :CONTINENTS (EU))
 (COUNTRY :NAME "Burkina Faso" :CAPITAL "Ouagadougou" :CONTINENTS (AF))
 (COUNTRY :NAME "Burma/Myanmar" :CAPITAL "Yangon" :CONTINENTS (AS))
 (COUNTRY :NAME "Burundi" :CAPITAL "Bujumbura" :CONTINENTS (AF))
 (COUNTRY :NAME "Cambodia" :CAPITAL "Phnom Penh" :CONTINENTS (AS))
 (COUNTRY :NAME "Cameroon" :CAPITAL "Yaounde" :CONTINENTS (AF))
 (COUNTRY :NAME "Canada" :CAPITAL "Ottawa" :CONTINENTS (NA))
 (COUNTRY :NAME "Cape Verde" :CAPITAL "Praia" :CONTINENTS (EU))
 (COUNTRY :NAME "Central African Republic" :CAPITAL "Bangui" :CONTINENTS (AF))
 (COUNTRY :NAME "Chad" :CAPITAL "N'Djamena" :CONTINENTS (AF))
 (COUNTRY :NAME "Chile" :CAPITAL "Santiago" :CONTINENTS (SA))
 (COUNTRY :NAME "China" :CAPITAL "Beijing" :CONTINENTS (AS))
 (COUNTRY :NAME "Colombia" :CAPITAL "Bogota" :CONTINENTS (SA))
 (COUNTRY :NAME "Comoros" :CAPITAL "Moroni" :CONTINENTS (AF))
 (COUNTRY :NAME "Congo" :CAPITAL "Brazzaville" :CONTINENTS (AF))
 (COUNTRY :NAME "Congo, Democratic Republic of" :CAPITAL "Kinshasa" :CONTINENTS
  (AF))
 (COUNTRY :NAME "Costa Rica" :CAPITAL "San Jose" :CONTINENTS (NA))
 (COUNTRY :NAME "Cote d'Ivoire/Ivory Coast" :CAPITAL "Yamoussoukro" :CONTINENTS
  (AF))
 (COUNTRY :NAME "Croatia" :CAPITAL "Zagreb" :CONTINENTS (EU))
 (COUNTRY :NAME "Cuba" :CAPITAL "Havana" :CONTINENTS (NA))
 (COUNTRY :NAME "Cyprus" :CAPITAL "Nicosia" :CONTINENTS (AS EU))
 (COUNTRY :NAME "Czech Republic" :CAPITAL "Prague" :CONTINENTS (EU))
 (COUNTRY :NAME "Denmark" :CAPITAL "Copenhagen" :CONTINENTS (EU))
 (COUNTRY :NAME "Djibouti" :CAPITAL "Djibouti" :CONTINENTS (AF))
 (COUNTRY :NAME "Dominica" :CAPITAL "Roseau" :CONTINENTS (NA))
 (COUNTRY :NAME "Dominican Republic" :CAPITAL "Santo Domingo" :CONTINENTS (NA))
 (COUNTRY :NAME "East Timor" :CAPITAL "Dili" :CONTINENTS (AS))
 (COUNTRY :NAME "Ecuador" :CAPITAL "Quito" :CONTINENTS (SA))
 (COUNTRY :NAME "Egypt" :CAPITAL "Cairo" :CONTINENTS (AF))
 (COUNTRY :NAME "El Salvador" :CAPITAL "San Salvador" :CONTINENTS (NA))
 (COUNTRY :NAME "Equatorial Guinea" :CAPITAL "Malabo" :CONTINENTS (AF))
 (COUNTRY :NAME "Eritrea" :CAPITAL "Asmara" :CONTINENTS (AF))
 (COUNTRY :NAME "Estonia" :CAPITAL "Tallinn" :CONTINENTS (EU))
 (COUNTRY :NAME "Ethiopia" :CAPITAL "Addis Ababa" :CONTINENTS (AF))
 (COUNTRY :NAME "Fiji" :CAPITAL "Suva" :CONTINENTS (AU))
 (COUNTRY :NAME "Finland" :CAPITAL "Helsinki" :CONTINENTS (EU))
 (COUNTRY :NAME "France" :CAPITAL "Paris" :CONTINENTS (EU))
 (COUNTRY :NAME "Gabon" :CAPITAL "Liberville" :CONTINENTS (AF))
 (COUNTRY :NAME "Gambia" :CAPITAL "Banjul" :CONTINENTS (AF))
 (COUNTRY :NAME "Georgia" :CAPITAL "Tbilisi" :CONTINENTS (EU))
 (COUNTRY :NAME "Germany" :CAPITAL "Berlin" :CONTINENTS (EU))
 (COUNTRY :NAME "Ghana" :CAPITAL "Accra" :CONTINENTS (AF))
 (COUNTRY :NAME "Greece" :CAPITAL "Athens" :CONTINENTS (EU))
 (COUNTRY :NAME "Grenada" :CAPITAL "St. George's" :CONTINENTS (NA))
 (COUNTRY :NAME "Guatemala" :CAPITAL "Guatemala City" :CONTINENTS (NA))
 (COUNTRY :NAME "Guinea" :CAPITAL "Conakry" :CONTINENTS (AF))
 (COUNTRY :NAME "Guinea-Bissau" :CAPITAL "Bissau" :CONTINENTS (AF))
 (COUNTRY :NAME "Guyana" :CAPITAL "Georgetown" :CONTINENTS (SA))
 (COUNTRY :NAME "Haiti" :CAPITAL "Port-au-Prince" :CONTINENTS (NA))
 (COUNTRY :NAME "Honduras" :CAPITAL "Tegucigalpa" :CONTINENTS (NA))
 (COUNTRY :NAME "Hungary" :CAPITAL "Budapest" :CONTINENTS (EU))
 (COUNTRY :NAME "Iceland" :CAPITAL "Reykjavik" :CONTINENTS (EU))
 (COUNTRY :NAME "India" :CAPITAL "New Delhi" :CONTINENTS (AS))
 (COUNTRY :NAME "Indonesia" :CAPITAL "Jakarta" :CONTINENTS (AS))
 (COUNTRY :NAME "Iran" :CAPITAL "Tehran" :CONTINENTS (AS))
 (COUNTRY :NAME "Iraq" :CAPITAL "Baghdad" :CONTINENTS (AS))
 (COUNTRY :NAME "Ireland" :CAPITAL "Dublin" :CONTINENTS (EU))
 (COUNTRY :NAME "Israel" :CAPITAL "Jerusalem" :CONTINENTS (AS))
 (COUNTRY :NAME "Italy" :CAPITAL "Rome" :CONTINENTS (EU))
 (COUNTRY :NAME "Jamaica" :CAPITAL "Kingston" :CONTINENTS (NA))
 (COUNTRY :NAME "Japan" :CAPITAL "Tokyo" :CONTINENTS (AS))
 (COUNTRY :NAME "Jordan" :CAPITAL "Amman" :CONTINENTS (AS))
 (COUNTRY :NAME "Kazakstan" :CAPITAL "Astana" :CONTINENTS (AS))
 (COUNTRY :NAME "Kenya" :CAPITAL "Nairobi" :CONTINENTS (AF))
 (COUNTRY :NAME "Kiribati" :CAPITAL "Bairiki" :CONTINENTS (AU))
 (COUNTRY :NAME "Korea, North" :CAPITAL "Pyongyang" :CONTINENTS (AS))
 (COUNTRY :NAME "Korea, South" :CAPITAL "Seoul" :CONTINENTS (AS))
 (COUNTRY :NAME "Kuwait" :CAPITAL "Kuwait City" :CONTINENTS (AS))
 (COUNTRY :NAME "Kyrgyzstan" :CAPITAL "Bishkek" :CONTINENTS (AS))
 (COUNTRY :NAME "Laos" :CAPITAL "Vientiane" :CONTINENTS (AS))
 (COUNTRY :NAME "Latvia" :CAPITAL "Riga" :CONTINENTS (EU))
 (COUNTRY :NAME "Lebanon" :CAPITAL "Beirut" :CONTINENTS (AS))
 (COUNTRY :NAME "Lesotho" :CAPITAL "Maseru" :CONTINENTS (AF))
 (COUNTRY :NAME "Liberia" :CAPITAL "Monrovia" :CONTINENTS (AF))
 (COUNTRY :NAME "Libya" :CAPITAL "Tripoli" :CONTINENTS (AF))
 (COUNTRY :NAME "Liechtenstein" :CAPITAL "Vaduz" :CONTINENTS (EU))
 (COUNTRY :NAME "Lithuania" :CAPITAL "Vilnius" :CONTINENTS (EU))
 (COUNTRY :NAME "Luxembourg" :CAPITAL "Luxembourg" :CONTINENTS (EU))
 (COUNTRY :NAME "Macedonia" :CAPITAL "Skopje" :CONTINENTS (EU))
 (COUNTRY :NAME "Madagascar" :CAPITAL "Antananarivo" :CONTINENTS (AF))
 (COUNTRY :NAME "Malawi" :CAPITAL "Lilongwe" :CONTINENTS (AF))
 (COUNTRY :NAME "Malaysia" :CAPITAL "Kuala Lumpur" :CONTINENTS (AS))
 (COUNTRY :NAME "Maldives" :CAPITAL "Male" :CONTINENTS (AS))
 (COUNTRY :NAME "Mali" :CAPITAL "Bamako" :CONTINENTS (AF))
 (COUNTRY :NAME "Malta" :CAPITAL "Valletta" :CONTINENTS (EU))
 (COUNTRY :NAME "Marshall Islands" :CAPITAL "Majuro" :CONTINENTS (AU))
 (COUNTRY :NAME "Mauritania" :CAPITAL "Nouakchott" :CONTINENTS (AF))
 (COUNTRY :NAME "Mauritius" :CAPITAL "Port Louis" :CONTINENTS (AF))
 (COUNTRY :NAME "Mexico" :CAPITAL "Mexico City" :CONTINENTS (NA))
 (COUNTRY :NAME "Micronesia" :CAPITAL "Palikir" :CONTINENTS (AU))
 (COUNTRY :NAME "Moldova" :CAPITAL "Chisinau" :CONTINENTS (EU))
 (COUNTRY :NAME "Monaco" :CAPITAL "Monaco" :CONTINENTS (EU))
 (COUNTRY :NAME "Mongolia" :CAPITAL "Ulan Bator" :CONTINENTS (AS))
 (COUNTRY :NAME "Montenegro" :CAPITAL "Podgorica" :CONTINENTS (EU))
 (COUNTRY :NAME "Morocco" :CAPITAL "Rabat" :CONTINENTS (AF))
 (COUNTRY :NAME "Mozambique" :CAPITAL "Maputo" :CONTINENTS (AF))
 (COUNTRY :NAME "Namibia" :CAPITAL "Windhoek" :CONTINENTS (AF))
 (COUNTRY :NAME "Nauru" :CAPITAL "no official capital" :CONTINENTS (AU))
 (COUNTRY :NAME "Nepal" :CAPITAL "Kathmandu" :CONTINENTS (AS))
 (COUNTRY :NAME "Netherlands" :CAPITAL "Amsterdam, The Hague" :CONTINENTS (EU))
 (COUNTRY :NAME "New Zealand" :CAPITAL "Wellington" :CONTINENTS (AU))
 (COUNTRY :NAME "Nicaragua" :CAPITAL "Managua" :CONTINENTS (NA))
 (COUNTRY :NAME "Niger" :CAPITAL "Niamey" :CONTINENTS (AF))
 (COUNTRY :NAME "Nigeria" :CAPITAL "Abuja" :CONTINENTS (AF))
 (COUNTRY :NAME "Norway" :CAPITAL "Oslo" :CONTINENTS (EU))
 (COUNTRY :NAME "Oman" :CAPITAL "Muscat" :CONTINENTS (AS))
 (COUNTRY :NAME "Pakistan" :CAPITAL "Islamabad" :CONTINENTS (AS))
 (COUNTRY :NAME "Palau" :CAPITAL "Koror" :CONTINENTS (AU))
 (COUNTRY :NAME "Panama" :CAPITAL "Panama City" :CONTINENTS (NA))
 (COUNTRY :NAME "Papua New Guinea" :CAPITAL "Port Moresby" :CONTINENTS (AU))
 (COUNTRY :NAME "Paraguay" :CAPITAL "Asuncion" :CONTINENTS (SA))
 (COUNTRY :NAME "Peru" :CAPITAL "Lima" :CONTINENTS (SA))
 (COUNTRY :NAME "Philippines" :CAPITAL "Manila" :CONTINENTS (AS))
 (COUNTRY :NAME "Poland" :CAPITAL "Warsaw" :CONTINENTS (EU))
 (COUNTRY :NAME "Portugal" :CAPITAL "Lisbon" :CONTINENTS (EU))
 (COUNTRY :NAME "Qatar" :CAPITAL "Doha" :CONTINENTS (AS))
 (COUNTRY :NAME "Romania" :CAPITAL "Bucharest" :CONTINENTS (EU))
 (COUNTRY :NAME "Russian Federation" :CAPITAL "Moscow" :CONTINENTS (AS EU))
 (COUNTRY :NAME "Rwanda" :CAPITAL "Kigali" :CONTINENTS (AF))
 (COUNTRY :NAME "Saint Kitts and Nevis" :CAPITAL "Basseterre" :CONTINENTS (NA))
 (COUNTRY :NAME "Saint Lucia" :CAPITAL "Castries" :CONTINENTS (NA))
 (COUNTRY :NAME "Saint Vincent and the Grenadines" :CAPITAL "Kingstown"
  :CONTINENTS (NA))
 (COUNTRY :NAME "Samoa" :CAPITAL "Apia" :CONTINENTS (AU))
 (COUNTRY :NAME "San Marino" :CAPITAL "San Marino" :CONTINENTS (EU))
 (COUNTRY :NAME "Sao Tome and Principe" :CAPITAL "Sao Tome" :CONTINENTS (AF))
 (COUNTRY :NAME "Saudi Arabia" :CAPITAL "Riyadh" :CONTINENTS (AS))
 (COUNTRY :NAME "Senegal" :CAPITAL "Dakar" :CONTINENTS (AF))
 (COUNTRY :NAME "Serbia" :CAPITAL "Belgrade" :CONTINENTS (EU))
 (COUNTRY :NAME "Seychelles" :CAPITAL "Victoria" :CONTINENTS (AF))
 (COUNTRY :NAME "Sierra Leone" :CAPITAL "Freetown" :CONTINENTS (AF))
 (COUNTRY :NAME "Singapore" :CAPITAL "Singapore City" :CONTINENTS (AS))
 (COUNTRY :NAME "Slovakia" :CAPITAL "Bratislava" :CONTINENTS (EU))
 (COUNTRY :NAME "Slovenia" :CAPITAL "Ljubljana" :CONTINENTS (EU))
 (COUNTRY :NAME "Solomon Islands" :CAPITAL "Honiara" :CONTINENTS (AU))
 (COUNTRY :NAME "Somalia" :CAPITAL "Mogadishu" :CONTINENTS (AF))
 (COUNTRY :NAME "South Africa" :CAPITAL "Pretoria, Cape Town, Bloemfontein"
  :CONTINENTS (AF))
 (COUNTRY :NAME "Spain" :CAPITAL "Madrid" :CONTINENTS (EU))
 (COUNTRY :NAME "Sri Lanka" :CAPITAL "Colombo" :CONTINENTS (AS))
 (COUNTRY :NAME "Sudan" :CAPITAL "Khartoum" :CONTINENTS (AF))
 (COUNTRY :NAME "Suriname" :CAPITAL "Paramaribo" :CONTINENTS (SA))
 (COUNTRY :NAME "Swaziland" :CAPITAL "Mbabane" :CONTINENTS (AF))
 (COUNTRY :NAME "Sweden" :CAPITAL "Stockholm" :CONTINENTS (EU))
 (COUNTRY :NAME "Switzerland" :CAPITAL "Bern" :CONTINENTS (EU))
 (COUNTRY :NAME "Syria" :CAPITAL "Damascus" :CONTINENTS (AS))
 (COUNTRY :NAME "Tajikistan" :CAPITAL "Dushanbe" :CONTINENTS (AS))
 (COUNTRY :NAME "Tanzania" :CAPITAL "Dodoma" :CONTINENTS (AF))
 (COUNTRY :NAME "Thailand" :CAPITAL "Bangkok" :CONTINENTS (AS))
 (COUNTRY :NAME "Togo" :CAPITAL "Lome" :CONTINENTS (AF))
 (COUNTRY :NAME "Tonga" :CAPITAL "Nuku'alofa" :CONTINENTS (AU))
 (COUNTRY :NAME "Trinidad and Tobago" :CAPITAL "Port-of-Spain" :CONTINENTS
  (NA))
 (COUNTRY :NAME "Tunisia" :CAPITAL "Tunis" :CONTINENTS (AF))
 (COUNTRY :NAME "Turkey" :CAPITAL "Ankara" :CONTINENTS (EU AS))
 (COUNTRY :NAME "Turkmenistan" :CAPITAL "Ashgabat" :CONTINENTS (AS))
 (COUNTRY :NAME "Tuvalu" :CAPITAL "Funafuti" :CONTINENTS (AU))
 (COUNTRY :NAME "Uganda" :CAPITAL "Kampala" :CONTINENTS (AF))
 (COUNTRY :NAME "Ukraine" :CAPITAL "Kiev" :CONTINENTS (EU))
 (COUNTRY :NAME "United Arab Emirates" :CAPITAL "Abu Dhabi" :CONTINENTS (AS))
 (COUNTRY :NAME "United Kingdom" :CAPITAL "London" :CONTINENTS (EU))
 (COUNTRY :NAME "United States" :CAPITAL "Washington D.C." :CONTINENTS (NA))
 (COUNTRY :NAME "Uruguay" :CAPITAL "Montevideo" :CONTINENTS (SA))
 (COUNTRY :NAME "Uzbekistan" :CAPITAL "Tashkent" :CONTINENTS (AS))
 (COUNTRY :NAME "Vanuatu" :CAPITAL "Port-Vila" :CONTINENTS (AU))
 (COUNTRY :NAME "Vatican City" :CAPITAL "na" :CONTINENTS (EU))
 (COUNTRY :NAME "Venezuela" :CAPITAL "Caracas" :CONTINENTS (SA))
 (COUNTRY :NAME "Vietnam" :CAPITAL "Hanoi" :CONTINENTS (AS))
 (COUNTRY :NAME "Yemen" :CAPITAL "Sana" :CONTINENTS (AS))
 (COUNTRY :NAME "Zambia" :CAPITAL "Lusaka" :CONTINENTS (AF))
 (COUNTRY :NAME "Zimbabwe" :CAPITAL "Harare" :CONTINENTS (AF))))

(defun country-continents (country)
  (seventh country))

(defun continent-code (continent)
  (fifth continent))

(defun is-in-two-p (country)
  (cdr (country-continents country)))

(defun is-in-continent-p (country continent) 
  (find (continent-code continent)
        (country-continents country)))

(defun contains-half-p (cont)
  (find-if (lambda (country)
             (and (is-in-continent-p country cont)
                  (is-in-two-p country)))
           *countries*))

(defun find-simple-continent ()
  (find-if (lambda (cont)
             (not (contains-half-p cont)))
           *continents*))
